#!/usr/bin/env python3
"""build_run_log.py — generate FINAL_RUN_LOG.md from round-folder CSVs.

This script is the ONLY writer of result numbers into any log (standing rule
5). It walks rounds/round-*/**/*.csv (legacy_quarantine excluded), renders
spec-style CSVs as tables, and lists everything else with shapes. Header records the
timestamp, git revision, and the active round from STATUS.md, so the overseer
can verify freshness (mtime newer than all CSVs, header line present).
"""
from __future__ import annotations

import datetime
import subprocess
import sys
from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parents[1]
ROUNDS = ROOT / "rounds"
DEST = ROOT / "FINAL_RUN_LOG.md"
SPEC_COLS = ["spec", "outcome", "variable", "coef", "se", "pval",
             "n_obs", "cluster_level", "stars_source"]
MAX_ROWS = 200


def git_rev() -> str:
    try:
        return subprocess.run(["git", "rev-parse", "--short", "HEAD"],
                              capture_output=True, text=True, timeout=10,
                              cwd=ROOT).stdout.strip() or "unknown"
    except Exception:  # noqa: BLE001
        return "unknown"


def active_round() -> str:
    status = ROOT / "STATUS.md"
    if status.is_file():
        for line in status.read_text(encoding="utf-8",
                                     errors="replace").splitlines():
            if line.strip():
                return line.strip()
    return "no STATUS.md header"


def fmt(x):
    if pd.isna(x):
        return ""
    if isinstance(x, float):
        return f"{x:.4g}"
    return str(x)


def render(df: pd.DataFrame, cols: list[str]) -> list[str]:
    lines = ["| " + " | ".join(cols) + " |",
             "|" + "|".join(["---"] * len(cols)) + "|"]
    for _, row in df.head(MAX_ROWS).iterrows():
        lines.append("| " + " | ".join(fmt(row.get(c)) for c in cols) + " |")
    if len(df) > MAX_ROWS:
        lines.append(f"| ... {len(df) - MAX_ROWS} more rows in the CSV ... |")
    return lines


def main() -> int:
    stamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    out = [f"# FINAL_RUN_LOG — generated {stamp} — git {git_rev()}",
           f"Active round: {active_round()}",
           "",
           "Generated by code/build_run_log.py. Every number below is read "
           "from a CSV; nothing is hand-typed. The CSVs remain ground truth.",
           ""]

    files = []
    if ROUNDS.is_dir():
        for rdir in sorted(ROUNDS.glob("round-*")):
            if rdir.is_dir():
                files += sorted(p for p in rdir.rglob("*.csv")
                                if "legacy_quarantine" not in p.parts)
    if not files:
        out.append("_No CSVs under rounds/round-*/ yet._")
    for f in files:
        rel = f.relative_to(ROOT)
        try:
            df = pd.read_csv(f)
        except Exception as exc:  # noqa: BLE001
            out += [f"## {rel}", f"_unreadable: {exc}_", ""]
            continue
        out.append(f"## {rel}  ({df.shape[0]} rows x {df.shape[1]} cols)")
        cols = {c.lower(): c for c in df.columns}
        if "coef" in cols:
            present = [cols[c] for c in SPEC_COLS if c in cols]
            out += render(df, present)
        else:
            out.append("Columns: " + ", ".join(map(str, df.columns)))
        out.append("")

    DEST.write_text("\n".join(out) + "\n", encoding="utf-8")
    print(f"wrote {DEST.relative_to(ROOT)} ({len(files)} CSVs)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
